#!/bin/bash

source /data/src/docker/joynr-base/scripts/ci/start-and-stop-gcd-service.sh
source /data/src/docker/joynr-base/scripts/ci/global.sh

cd /data/src

# fail on first error
# exit immediately if a command exits with a non-zero status
# print commands before they are executed
set -e

function usage
{
  echo "usage: javascript-clean-build [--skipTests]"
}

SKIPTESTS='false'

while [ "$1" != "" ]; do
  case $1 in
    --skipTests )           SKIPTESTS='true'
                            ;;
    * )                     usage
                            exit 1
  esac
  shift
done

log "Print node version"
if [ -f $NVM_DIR/nvm.sh ]
then
    source $NVM_DIR/nvm.sh
    echo "NVM version:"
    nvm --version
    echo "NVM list"
    nvm list
fi
echo "NODE version:"
node --version
echo "NPM version:"
npm --version

(
  log "INSTALL JOYNR BASE MODEL, TOOLS AND INFRASTRUCTURE SERVICES"
  mvn clean install -P no-license-and-notice,no-java-formatter,no-checkstyle -DskipTests
)

if [ "$SKIPTESTS" == "false" ]
then
    echo '####################################################'
    echo '# start services'
    echo '####################################################'

    /data/src/docker/joynr-base/scripts/ci/start-db.sh

    mosquitto -c /data/src/docker/joynr-base/mosquitto.conf &
    MOSQUITTO_PID=$!

    function stopservices
    {
        echo '####################################################'
        echo '# stop services'
        echo '####################################################'

        stopGcd

        echo "stop mosquitto"
        kill -TERM $MOSQUITTO_PID
        wait $MOSQUITTO_PID
        /data/src/docker/joynr-base/scripts/ci/stop-db.sh
    }

    set +e # stop services even if there are failing tests or startGcd fails
    startGcd
    SUCCESS=$?
    if [ "$SUCCESS" != "0" ];
    then
        echo '########################################################'
        echo '# Start GCD failed with exit code:' $SUCCESS
        echo '########################################################'

        stopservices
        exit $SUCCESS
    fi
fi

(
    log "building joynr JavaScript API"
    cd javascript
    mvn clean install \
    -Dskip.copy-notice-file=true \
    -Dskip.unpack-license-info=true \
    -DskipTests=$SKIPTESTS
    SUCCESS=$?

    if [ "$SUCCESS" == "0" ];
    then
        log "building joynr npm generator"
        cd ../tools/generator/joynr-generator-npm
        mvn clean install
        SUCCESS=$?
    fi
    exit $SUCCESS
)
EXIT_CODE=$?

set -e
if [ "$SKIPTESTS" == "false" ]
then
    stopservices
fi

exit $EXIT_CODE
