#!/bin/bash

echo "Launching docker containers"
docker-compose up -d
sleep 2

while [ -z "$(docker logs --tail 50 consumer 2>&1 | grep FINISHED)" ]; do
	echo "Waiting for scenario to finish ..."
	sleep 10
done

echo "Scenario finished. Checking for success."

echo "Obtaining and writing consumer logs"
CONSUMER_LOG="$(docker logs consumer 2>&1)"
echo "$CONSUMER_LOG" > consumer.log
echo "Analysing logs"

SUCCESS='[SUCCESS]'
FAIL="[FAIL]"
LOG_BEFORE_PFS="$(grep 'Messages processed before prepare for shutdown signal fired:' consumer.log)"
LOG_AFTER_PFS="$(grep 'Messages created after prepare for shutdown signal fired:' consumer.log)"
LOG_DURING_PFS="$(grep 'Messages created before prepare for shutdown signal fired but processed after:' consumer.log)"

if [[ $LOG_BEFORE_PFS == *"$SUCCESS"* ]] && [[ $LOG_AFTER_PFS == *"$SUCCESS"* ]] && [[ $LOG_DURING_PFS == *"$SUCCESS"* ]]; then
  echo SUCCESS
else
  if [[ $LOG_BEFORE_PFS == *"$FAIL"* ]]; then
    echo "$LOG_BEFORE_PFS"
  else
    echo "Not found log entry about messages processed before prepare for shutdown signal fired."
  fi
  if [[ $LOG_AFTER_PFS == *"$FAIL"* ]]; then
    echo "$LOG_AFTER_PFS"
  else
      echo "Not found log entry about messages created after prepare for shutdown signal fired."
  fi
  if [[ $LOG_DURING_PFS == *"$FAIL"* ]]; then
    echo "$LOG_DURING_PFS"
  else
      echo "Not found log entry about messages created before prepare for shutdown signal fired but processed after."
  fi
  echo FAILED
fi

docker-compose stop
docker-compose rm -f
