#!/bin/bash

docker-compose up -d
sleep 2
while [ -z "$(docker logs --tail 50 consumer 2>&1 | grep FINISHED)" ]; do
	echo "Waiting for scenario to finish ..."
	sleep 10
done

echo "Scenario finished. Checking for success."
CONSUMER_LOG="$(docker logs consumer 2>&1)"

PREPARE_FOR_SHUTDOWN_FOUND="$(echo ${CONSUMER_LOG} | grep 'Provider is preparing for shutdown. Message not sent.')"
FAILURE_REPORT_NOT_EMPTY="$(echo ${CONSUMER_LOG} | grep 'Second level failure report:' | sed 's/.*Second level failure report://')"
if [ ! -z "${PREPARE_FOR_SHUTDOWN_FOUND}" ] && [ ! -z "${FAILURE_REPORT_NOT_EMPTY}" ] ; then
	echo SUCCESS
else
	echo FAILED
	echo ${PREPARE_FOR_SHUTDOWN_FOUND}
	echo ${FAILURE_REPORT_NOT_EMPTY}
fi

docker-compose stop
docker-compose rm -f
