#ifndef JOYNRUTIL_H_
#define JOYNRUTIL_H_

#define JOYNR_MAJOR_VERSION (@JOYNR_MAJOR_VERSION@)
#define JOYNR_MINOR_VERSION (@JOYNR_MINOR_VERSION@)
#define JOYNR_PATCH_VERSION (@JOYNR_PATCH_VERSION@)
#define JOYNR_VERSION_STRING "@JOYNR_VERSION@"

#endif /* JOYNRUTIL_H_ */
