#!/bin/bash
set -e

function usage
{
    echo "usage: joynr-docker build | push | pull | remove"
    echo "       [--repository mydockerrepo.org]"
    echo "       [--version versionnumber]"
    echo "       [--additionaltags|-a <comma-separated list of tags>]"
    echo "       [--proxy_host <hostname> --proxy_port <portnumber>]"
    echo "       [--proxy_user <proxy user> --proxy_password <proxy password>]"
}

repository=
version=latest
command=$1
additionaltags=latest
proxy_host=
proxy_port=
proxy_user=
proxy_password=
shift
echo "after command: $1"

echo "in params: $1"
# if repository is set, add a single trailing slash
# if it was passed in with the slash, this is removed first
while [ "$1" != "" ]; do
echo "PARAM is: $1"
    case $1 in
        -r | --repository )     shift
                                echo "REPO"
                                repository=${1%/}/
                                ;;
        -v | --version )        shift
                                version="$1"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        -a | --additionaltags )  shift
                                additionaltags=$1
                                ;;
        -H | --proxy_host )     shift
                                proxy_host=$1
                                ;;
        -P | --proxy_port )     shift
                                proxy_port=$1
                                ;;
        -U | --proxy_user )     shift
                                proxy_user=$1
                                ;;
        -p | --proxy_password )     shift
                                proxy_password=$1
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

#list of available images
declare -a listOfImages=(
    "joynr-base"
    "joynr-java"
    "joynr-android"
    "joynr-javascript"
    "joynr-cpp-base"
    "joynr-cpp-gcc"
    "joynr-cpp-clang"
    "joynr-runtime-environment-base"
    "joynr-ilt-gcc"
)

function build
{
    for image in "${listOfImages[@]}"
    do
        proxy_arg=""
        if [ -n "$proxy_host" ]
        then
            if [ -z "$proxy_port" ]
            then
                echo "proxy_port not defined."
                usage
                exit 1
            fi

            proxy_user_pass=""
            if [ -n "$proxy_user" ]
            then
                if [ -z "$proxy_password" ]
                then
                    echo "proxy_passsword not defined."
                    usage
                    exit 1
                fi
                proxy_user_pass="--build-arg PROXY_USER_BUILD_ARG=$proxy_user --build-arg PROXY_PASSWORD_BUILD_ARG=$proxy_password"
            fi

            proxy_arg="--build-arg PROXY_HOST_BUILD_ARG=$proxy_host --build-arg PROXY_PORT_BUILD_ARG=$proxy_port $proxy_user_pass"
        fi
        echo "building image: ${image}:latest"
        docker build $proxy_arg -t ${image}:latest ${image}/

    done
     
    if [[ "$additionaltags" != "latest" ]] || [[ "$version" != "latest" ]]; then
        for image in "${listOfImages[@]}"
        do
            IFS=',' read -ra tags <<< "$additionaltags"    #Convert string to array
            tags+=("$version")
            for tag in "${tags[@]}"; do
                echo "tagging image ${repository}${image}:latest with tag ${tag}"
                docker tag ${image}:latest ${repository}${image}:${tag}
                docker tag ${image}:latest ${image}:${tag}
            done
        done
    fi
}

function pull
{
    echo "pulling from repository: $repository for version:$version"
    for image in "${listOfImages[@]}"
    do
        docker pull ${repository}${image}:${version}
    done
}

function push
{
    echo "pushing to repository: $repository with version:$version"
    for image in "${listOfImages[@]}"
    do
        docker push ${repository}${image}:${version}

        IFS=',' read -ra tags <<< "$additionaltags"    #Convert string to array

        for tag in "${tags[@]}"; do
            docker push ${repository}${image}:${tag}
        done

    done
}

function remove
{
    echo "removing from repository: $repository version:$version"
    repositoryurl=$repository
    if [[ "$repositoryurl" == *"v2"* ]]
    then
        echo "repository name already equipped with docker specific namespaces. Skipping repository name modification..."
        repository=`echo $repository | cut -d'/' -f1`/`echo $repository | cut -d'/' -f3-`
    else
        repositoryurl=`echo $repository | cut -d'/' -f1`/v2/`echo $repository | cut -d'/' -f2-`
        echo "repository name $repository is not equipped with docker specific namespaces. Modified repository name: $repositoryurl"
    fi
    for image in "${listOfImages[@]}"
    do
        docker rmi ${repository}${image}:${version}
        digest=`curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' -s -I https://${repositoryurl}${image}/manifests/${version} | grep 'Docker-Content-Digest' | cut -d':' -f2- | cut -d\  -f2- | tr -d '\r'`
        if [ -z "$digest" ]
        then
            echo "Docker-Content-Digest for docker image ${repository}${image}:${version} not found. Skipping tag removal..."
        else
            echo "Docker-Content-Digest for docker image ${repository}${image}:${version} found: ${digest}. Deleting tag"
            curl --request DELETE https://${repositoryurl}${image}/manifests/${digest}
        fi
    done
}

case $command in
    build )                 build
                            exit
                            ;;
    push )                  push
                            exit
                            ;;
    pull )                  pull
                            exit
                            ;;
    remove )                remove
                            exit
                            ;;
    * )                     usage
                            exit 1
esac
