/*
* This file was generated by the CommonAPI Generators.
*
*/
#ifndef JOYNR_MESSAGING_I_Capabilities_H_
#define JOYNR_MESSAGING_I_Capabilities_H_

#include <CommonAPI/types.h>

namespace joynr {
namespace messaging {

class ICapabilities {
 public:
    virtual ~ICapabilities() { }

    static inline const char* getInterfaceId();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* ICapabilities::getInterfaceId() {
    return "joynr.messaging.ICapabilities";
}

CommonAPI::Version ICapabilities::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}


} // namespace messaging
} // namespace joynr

namespace CommonAPI {

}


namespace std {
}

#endif // JOYNR_MESSAGING_I_Capabilities_H_
