/*
* This file was generated by the CommonAPI Generators.
*
*/
#include "IMessaging.h"

namespace joynr {
namespace messaging {

IMessaging::JoynrMessage::JoynrMessage(const std::string& typeValue, const types::Types::JoynrMessageHeader& headerValue, const std::string& payloadValue):
        type(typeValue),
        header(headerValue),
        payload(payloadValue)
{
}

bool operator==(const IMessaging::JoynrMessage& lhs, const IMessaging::JoynrMessage& rhs) {
    if (&lhs == &rhs)
        return true;

    return
        lhs.type == rhs.type &&
        lhs.header == rhs.header &&
        lhs.payload == rhs.payload
    ;
}

void IMessaging::JoynrMessage::readFromInputStream(CommonAPI::InputStream& inputStream) {
    inputStream >> type;
    inputStream >> header;
    inputStream >> payload;
}

void IMessaging::JoynrMessage::writeToOutputStream(CommonAPI::OutputStream& outputStream) const {
    outputStream << type;
    outputStream << header;
    outputStream << payload;
}

} // namespace messaging
} // namespace joynr
