/*
* This file was generated by the CommonAPI Generators.
*
*/
#include <joynr/messaging/IMessagingStubDefault.h>

namespace joynr {
namespace messaging {

IMessagingStubDefault::IMessagingStubDefault():
        remoteEventHandler_(this) {
}

IMessagingStubRemoteEvent* IMessagingStubDefault::initStubAdapter(const std::shared_ptr<IMessagingStubAdapter>& stubAdapter) {
    stubAdapter_ = stubAdapter;
    return &remoteEventHandler_;
}


void IMessagingStubDefault::transmit(IMessaging::JoynrMessage message, types::Types::JoynrMessageQos qos) {
    // No operation in default
}



IMessagingStubDefault::RemoteEventHandler::RemoteEventHandler(IMessagingStubDefault* defaultStub):
        defaultStub_(defaultStub) {
}

} // namespace messaging
} // namespace joynr
